# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: jcm
version: "0.0.2"
slug: example
description: Jiang Cluster Management
url: "https://github.com/XiaoXianNv-boot/hassio_jcm"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw 
  - homeassistant_config:rw
  - media:rw
options:
  user: "admin"
  password: "admin"
  port: "8888"
schema:
  user: "str?"
  password: "str?"
  port: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
advanced: false
