# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: jcm
version: "1.0.7"
slug: jcm
description: Jiang Cluster Management
url: "https://github.com/XiaoXianNv-boot/hassio_jcm"
startup: system
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ingress: true
ingress_port: 8888
ingress_stream: true
init: false
uart: true
udev: true
usb: true
hassio_api: true
hassio_role: admin
homeassistant_api: true
docker_api: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
full_access: true
audio: true
video: true
stdin: true
auth_api: true
devices:
  - /dev/mem
  - /etc/timezone
image: xiaoxiannvboot/{arch}-hassio_jcm
map:
  - share:rw
  - homeassistant_config:rw
  - media:rw
  - addon_config:rw
  - ssl:rw
  - addons:rw
  - backup:rw
  - share:rw
  - all_addon_configs:rw
options:
  user: "admin"
  password: "admin"
  port: "8888"
schema:
  user: "str?"
  password: "str?"
  port: "str?"
advanced: false
host_network: true

