name: Docker Image CI

on:
  push:
    branches: [ "mainn" ]
  pull_request:
    branches: [ "mainn" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd jcm && docker build . --file Dockerfile --tag my-image-name:$(date +%s)
